spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CH03?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create