spring:
  application:
    name: springdatajpa
  datasource:
    url: jdbc:mysql://localhost:3306/CH05?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      ddl-auto: create


